package computerdatabase

import computerdatabase.Headers.{headers_12, headers_143, headers_578, uri3}
import io.gatling.core.Predef._
import io.gatling.http.Predef._

object SLP_PDP_CART {

  val p1 = exec(http("SLP_S1")
    .get(uri3 + "/en_US/search/?text=${pro-code1}&boxsearchBy=easyAskSearchTermSearchStrategy&boxea_path=&boxea_rpp=&boxea_cp=&boxea_sort=")
    .headers(headers_143))
    .pause(15)
     .exec(http("Product_PDP1")
    .get(uri3 + "${s1}/FSX/${purl1}")
    .headers(headers_12)
    .check(regex("""<input type="hidden" name="CSRFToken" value="([^"]*)" />""").saveAs("requestVerificationToken")))
    .pause(2)
     .exec(http("ATC_1")
    .post(uri3 + "${s1}/cart/addOffer")
    .headers(headers_578)
    .formParam("productCodePost", "${offer-code1}")
    .formParam("presetPriceValue", "0.0")
    .formParam("qty", "1")
    .formParam("CSRFToken", "${requestVerificationToken}"))
    .pause(2)

  val p2 = exec(http("SLP_S2")
    .get(uri3 + "/en_US/search/?text=${pro-code2}&boxsearchBy=easyAskSearchTermSearchStrategy&boxea_path=&boxea_rpp=&boxea_cp=&boxea_sort=")
    .headers(headers_143))
    .pause(15)
  .exec(http("Product_PDP2")
    .get(uri3 + "${s1}/FSX/${purl2}")
    .headers(headers_12)
    .check(regex("""<input type="hidden" name="CSRFToken" value="([^"]*)" />""").saveAs("requestVerificationToken")))
    .pause(2)
  .exec(http("ATC_2")
    .post(uri3 + "${s1}/cart/addOffer")
    .headers(headers_578)
    .formParam("productCodePost", "${offer-code2}")
    .formParam("presetPriceValue", "0.0")
    .formParam("qty", "1")
    .formParam("CSRFToken", "${requestVerificationToken}"))
    .pause(2)

  val p3 = exec(http("SLP_S3")
    .get(uri3 + "/en_US/search/?text=${pro-code3}&boxsearchBy=easyAskSearchTermSearchStrategy&boxea_path=&boxea_rpp=&boxea_cp=&boxea_sort=")
    .headers(headers_143))
    .pause(15)
  .exec(http("Product_PDP3")
    .get(uri3 + "${s1}/FSX/${purl3}")
    .headers(headers_12)
    .check(regex("""<input type="hidden" name="CSRFToken" value="([^"]*)" />""").saveAs("requestVerificationToken")))
    .pause(2)
  .exec(http("ATC_3")
    .post(uri3 + "${s1}/cart/addOffer")
    .headers(headers_578)
    .formParam("productCodePost", "${offer-code3}")
    .formParam("presetPriceValue", "0.0")
    .formParam("qty", "1")
    .formParam("CSRFToken", "${requestVerificationToken}"))
    .pause(2)

  val p4 = exec(http("SLP_S4")
    .get(uri3 + "/en_US/search/?text=${pro-code4}&boxsearchBy=easyAskSearchTermSearchStrategy&boxea_path=&boxea_rpp=&boxea_cp=&boxea_sort=")
    .headers(headers_143))
    .pause(15)
  .exec(http("Product_PDP4")
    .get(uri3 + "${s1}/FSX/${purl4}")
    .headers(headers_12)
    .check(regex("""<input type="hidden" name="CSRFToken" value="([^"]*)" />""").saveAs("requestVerificationToken")))
    .pause(2)
  .exec(http("ATC_4")
    .post(uri3 + "${s1}/cart/addOffer")
    .headers(headers_578)
    .formParam("productCodePost", "${offer-code4}")
    .formParam("presetPriceValue", "0.0")
    .formParam("qty", "1")
    .formParam("CSRFToken", "${requestVerificationToken}"))
    .pause(2)

}
